using System;
using System.Collections.Generic;
using UbiArt.ITF;

namespace UbiArt {
	public class MemoryData_ChildOfLightPC : IMemoryData {
		#region Data
		public static readonly Dictionary<Type, uint> EditorSizes = new Dictionary<Type, uint> {
			// Main
			[typeof(StringID)] = 8,
			[typeof(Path)] = 100, // 92 + StringID
			[typeof(LocalizedPath)] = 104, // Path + LocId
			[typeof(LocalisationId)] = 4,
			[typeof(ColorInteger)] = 4,
			[typeof(string)] = 20,
			[typeof(Vec2d)] = 8,
			[typeof(Vec3d)] = 12,
			[typeof(Vec4d)] = 16,
			[typeof(Color)] = 16,
			[typeof(Angle)] = 4,
			[typeof(AngleAmount)] = 4,
			[typeof(ObjectId)] = 16,
			[typeof(ObjectRef)] = 4,
			[typeof(PathRef)] = 4,
			[typeof(Platform)] = 4,
			[typeof(SoundGUID)] = 8,
			[typeof(Volume)] = 4,

			// From game data
			[typeof(ITF.FriseConfig)] = 1200,
			[typeof(ITF.CollisionFrieze)] = 44,
			[typeof(ITF.FillConfig)] = 40,
			[typeof(ITF.FriseTextureConfig)] = 1852,
			[typeof(ITF.GFXMaterialSerializable)] = 1660,
			[typeof(ITF.GFXMaterialTexturePathSet)] = 900,
			[typeof(ITF.GFXMaterialSerializableParam)] = 24,
			[typeof(ITF.CollisionTexture)] = 32,
			[typeof(ITF.VertexAnim)] = 44,
			[typeof(ITF.FluidConfig)] = 276,
			[typeof(ITF.FluidFriseLayer)] = 268,
			[typeof(ITF.GFXPrimitiveParam)] = 80,
			[typeof(ITF.Actor_Template)] = 188,
			[typeof(ITF.FogBoxComponent_Template)] = 16,
			[typeof(ITF.FXControllerComponent_Template)] = 140,
			[typeof(ITF.FXControl)] = 128,
			[typeof(ITF.FxBankComponent_Template)] = 1900,
			[typeof(ITF.AABB)] = 16,
			[typeof(ITF.FxDescriptor_Template)] = 5260,
			[typeof(ITF.ITF_ParticleGenerator_Template)] = 3288,
			[typeof(ITF.ParticleGeneratorParameters)] = 3012,
			[typeof(ITF.ParPhase)] = 92,
			[typeof(ITF.ParLifeTimeCurve)] = 72,
			[typeof(ITF.Spline)] = 36,
			[typeof(ITF.EmitLifeTimeCurve)] = 72,
			[typeof(ITF.ProceduralInputData)] = 36,
			[typeof(ITF.GFXMaterialShader_Template)] = 548,
			[typeof(ITF.GFX_MaterialParams)] = 104,
			[typeof(ITF.COL_GFXMaterialShader_Layer_Template)] = 60,
			[typeof(ITF.COL_GameMaterial_Template)] = 244,
			[typeof(ITF.ClearColorComponent_Template)] = 16,
			[typeof(ITF.TweenComponent_Template)] = 120,
			[typeof(ITF.LinkComponent_Template)] = 56,
			[typeof(ITF.SoundComponent_Template)] = 112,
			[typeof(ITF.TextureGraphicComponent_Template)] = 3520,
			[typeof(ITF.COL_PhysBodyComponent_Template)] = 24,
			[typeof(ITF.PhysShapeCircle)] = 8,
			[typeof(ITF.COL_PendulumComponent_Template)] = 32,
			[typeof(ITF.LinkCurveComponent_Template)] = 3524,
			[typeof(ITF.SoundDescriptor_Template)] = 96,
			[typeof(ITF.WwiseInputDesc)] = 28,
			[typeof(ITF.AnimLightComponent_Template)] = 2352,
			[typeof(ITF.SubAnimSet_Template)] = 416,
			[typeof(ITF.SubAnim_Template)] = 188,
			[typeof(ITF.AnimResourcePackage)] = 240,
			[typeof(ITF.TextureBankPath)] = 1108,
			[typeof(ITF.AnimPathAABB)] = 124,
			[typeof(ITF.COL_PointOfInterestComponent_Template)] = 20,
			[typeof(ITF.PhysShapePolygon)] = 96,
			[typeof(ITF.BoxInterpolatorComponent_Template)] = 48,
			[typeof(ITF.AFXPostProcessComponent_Template)] = 144,
			[typeof(ITF.InputDesc)] = 12,
			[typeof(ITF.ProceduralBoneComponent_Template)] = 16,
			[typeof(ITF.BezierTreeComponent_Template)] = 100,
			[typeof(ITF.BezierBranchGrowComponent_Template)] = 4,
			[typeof(ITF.MultipassBranchRendererComponent_Template)] = 4,
			[typeof(ITF.BezierBranchBoneComponent_Template)] = 4,
			[typeof(ITF.BezierBranchFxComponent_Template)] = 36,
			[typeof(ITF.FlexMeshBranchComponent_Template)] = 4,
			[typeof(ITF.TweenInterpreter_Template)] = 24,
			[typeof(ITF.TweenInstructionSet_Template)] = 44,
			[typeof(ITF.TweenLine_Template)] = 116,
			[typeof(ITF.TweenWait_Template)] = 16,
			[typeof(ITF.MultipassTreeRendererComponent_Template)] = 1824,
			[typeof(ITF.BezierBranchRendererPass_Template)] = 1856,
			[typeof(ITF.BezierCurveRenderer_Template)] = 1824,
			[typeof(ITF.BezierBranchRendererSegment_Template)] = 92,
			[typeof(ITF.BezierBranchPolylineComponent_Template)] = 152,
			[typeof(ITF.BezierBranchRendererComponent_Template)] = 4,
			[typeof(ITF.BezierTreeRendererComponent_Template)] = 3680,
			[typeof(ITF.PlayerDetectorComponent_Template)] = 112,
			[typeof(ITF.TriggerComponent_Template)] = 92,
			[typeof(ITF.EventTrigger)] = 32,
			[typeof(ITF.DialogActorComponent_Template)] = 228,
			[typeof(ITF.MoveChildrenComponent_Template)] = 20,
			[typeof(ITF.COL_CharacterInfoComponent_Template)] = 24,
			[typeof(ITF.COL_FeedbackControllerComponent_Template)] = 148,
			[typeof(ITF.UIMenuBasic_Template)] = 72,
			[typeof(ITF.UIComponent_Template)] = 28,
			[typeof(ITF.MaskResolverComponent_Template)] = 24,
			[typeof(ITF.COL_SimplePatchComponent_Template)] = 3524,
			[typeof(ITF.CheckpointComponent_Template)] = 20,
			[typeof(ITF.PrefetchTargetComponent_Template)] = 16,
			[typeof(ITF.COL_TeleportTargetComponent_Template)] = 16,
			[typeof(ITF.COL_InteractiveObjectComponent_Template)] = 24,
			[typeof(ITF.MissionComponent_Template)] = 16,
			[typeof(ITF.PhantomComponent_Template)] = 100,
			[typeof(ITF.CameraModifierComponent_Template)] = 380,
			[typeof(ITF.CamModifier_Template)] = 356,
			[typeof(ITF.AnimatedComponent_Template)] = 2520,
			[typeof(ITF.AnimTree_Template)] = 120,
			[typeof(ITF.AnimTreeNodePlayAnim_Template)] = 168,
			[typeof(ITF.BlendTreeTransition_Template<ITF.AnimTreeResult>)] = 180,
			[typeof(ITF.COL_BattleTriggerComponent_Template)] = 196,
			[typeof(ITF.COL_BattleSetupsConfig)] = 124,
			[typeof(ITF.COL_BattleSetupsConfig.BattleSetup)] = 24,
			[typeof(ITF.COL_BattleSetupsConfig.BattleEnemy)] = 20,
			[typeof(ITF.COL_SpawnedNPCComponent_Template)] = 16,
			[typeof(ITF.SoundBankComponent_Template)] = 24,
			[typeof(ITF.StickToPolylinePhysComponent_Template)] = 200,
			[typeof(ITF.GroundAIControllerComponent_Template)] = 180,
			[typeof(ITF.COL_BTAIComponent_Template)] = 88,
			[typeof(ITF.BehaviorTree_Template)] = 32,
			[typeof(ITF.BTNodeTemplate_Ref)] = 12,
			[typeof(ITF.BTDecider_Template)] = 56,
			[typeof(ITF.COL_BTActionStunned_Template)] = 88,
			[typeof(ITF.BTDeciderHasFact_Template)] = 96,
			[typeof(ITF.BTSequence_Template)] = 32,
			[typeof(ITF.BTActionSetFact_Template)] = 84,
			[typeof(ITF.BTActionPlayAnim_Template)] = 84,
			[typeof(ITF.COL_BTActionRoaming_Template)] = 80,
			[typeof(ITF.COL_BTActionRangeAttack_Template)] = 180,
			[typeof(ITF.COL_BTActionCharge_Template)] = 68,
			[typeof(ITF.COL_BTActionAlerted_Template)] = 96,
			[typeof(ITF.BTActionStayIdle_Template)] = 84,
			[typeof(ITF.BTDeciderHasPlayerNear_Template)] = 76,
			[typeof(ITF.BTActionRemoveFact_Template)] = 60,
			[typeof(ITF.COL_PolygonWindComponent_Template)] = 36,
			[typeof(ITF.PolylineComponent_Template)] = 40,
			[typeof(ITF.COL_TeleporterComponent_Template)] = 16,
			[typeof(ITF.COL_BezierBranchLightOrbChainLinkRendererComponent_Template)] = 12,
			[typeof(ITF.AnimMeshVertexComponent_Template)] = 3832,
			[typeof(ITF.COL_LightOrbChainComponent_Template)] = 600,
			[typeof(ITF.PlayAnimOnEventReceiveComponent_Template)] = 96,
			[typeof(ITF.RenderBoxComponent_Template)] = 7004,
			[typeof(ITF.RenderSingleAnimData)] = 80,
			[typeof(ITF.TextBoxComponent_Template)] = 72,
			[typeof(ITF.FontTextArea.Style)] = 800,
			[typeof(ITF.FontTextArea.FontSet)] = 600,
			[typeof(ITF.TextAnimScaleComponent_Template)] = 64,
			[typeof(ITF.COL_TutorialActorComponent_Template)] = 16,
			[typeof(ITF.COL_BTActionFollowCurve_Template)] = 80,
			[typeof(ITF.TweenComponent_Template.InstructionSet)] = 132,
			[typeof(ITF.TweenEvent_Template)] = 40,
			[typeof(ITF.EventShow)] = 56,
			[typeof(ITF.EventGeneric)] = 28,
			[typeof(ITF.AABBComponent_Template)] = 16,
			[typeof(ITF.COL_LightConcentratorComponent_Template)] = 16,
			[typeof(ITF.COL_MovableObject_Template)] = 72,
			[typeof(ITF.COL_WheelPuzzleComponent_Template)] = 16,
			[typeof(ITF.PolylineParameters)] = 192,
			[typeof(ITF.SequencePlayerComponent_Template)] = 236,
			[typeof(ITF.PlayGameplay_evtTemplate)] = 184,
			[typeof(ITF.ObjectPath)] = 48,
			[typeof(ITF.EventLockPlayers)] = 36,
			[typeof(ITF.COL_EventHUDDisplay)] = 20,
			[typeof(ITF.PlayTrajectory_evtTemplate)] = 472,
			[typeof(ITF.Trajectory_Template)] = 128,
			[typeof(ITF.Spline.SplinePoint)] = 72,
			[typeof(ITF.BoolEventList)] = 24,
			[typeof(ITF.SequenceTrackInfo_Template)] = 48,
			[typeof(ITF.BezierTreeFollowComponent_Template)] = 16,
			[typeof(ITF.Unknown_COL_25_sub_958920)] = 64,
			[typeof(ITF.PlayText_evtTemplate)] = 176,
			[typeof(ITF.COL_UIEventHideTutorial)] = 24,
			[typeof(ITF.COL_UIEventDisplayTutorial)] = 24,
			[typeof(ITF.EnvironmentComponent_Template)] = 16,
			[typeof(ITF.COL_SpiderControllerComponent_Template)] = 16,
			[typeof(ITF.COL_BTActionRoamingVertical_Template)] = 76,
			[typeof(ITF.BezierBranchWeightComponent_Template)] = 48,
			[typeof(ITF.PlaySound_evtTemplate)] = 172,
			[typeof(ITF.BoolEventList.BoolEvent)] = 12,
			[typeof(ITF.PlaySpawn_evtTemplate)] = 348,
			[typeof(ITF.PlayAnim3D_evtTemplate)] = 232,
			[typeof(ITF.EventSequenceFade)] = 28,
			[typeof(ITF.PlaySkip_evtTemplate)] = 76,
			[typeof(ITF.COL_EventStartCinematicDialog)] = 68,
			[typeof(ITF.COL_CinematicDialogData)] = 52,
			[typeof(ITF.MoviePlayerComponent_Template)] = 2648,
			[typeof(ITF.EventPlayMovie)] = 20,
			[typeof(ITF.COL_EventTeleportToCheckpoint)] = 36,
			[typeof(ITF.COL_EventGotoRequest)] = 56,
			[typeof(ITF.COL_EventInventoryItemAttachement)] = 28,
			[typeof(ITF.Mesh3DComponent_Template)] = 2476,
			[typeof(ITF.Animation3DTree_Template)] = 120,
			[typeof(ITF.Animation3DTreeNodePlayAnim_Template)] = 160,
			[typeof(ITF.Animation3DSet_Template)] = 24,
			[typeof(ITF.Animation3DInfo_Template)] = 148,
			[typeof(ITF.FluidEffectsComponent_Template)] = 80,
			[typeof(ITF.FluidEffectsComponent_Template.CollisionRig)] = 20,
			[typeof(ITF.FluidEffectsComponent_Template.Capsule)] = 28,
			[typeof(ITF.FluidEffectsComponent_Template.HairMeshTemplate)] = 320,
			[typeof(ITF.COL_InventoryAssetsComponent_Template)] = 64,
			[typeof(ITF.PhysShapeBox)] = 104,
			[typeof(ITF.COL_LightPuzzleComponent_Template)] = 16,
			[typeof(ITF.COL_LightPuzzlePieceComponent_Template)] = 16,
			[typeof(ITF.EventPadRumbleStart)] = 24,
			[typeof(ITF.ObjectPath.Level)] = 24,
			[typeof(ITF.EventPlayWwiseEvent)] = 32,
			[typeof(ITF.COL_DoorComponent_Template)] = 24,
			[typeof(ITF.COL_CinematicDialogData.LineModifier)] = 48,
			[typeof(ITF.PlayAnim_evtTemplate)] = 328,
			[typeof(ITF.COL_EventDisableAutoFly)] = 16,
			[typeof(ITF.COL_EventEnableAutoFly)] = 20,
			[typeof(ITF.EventPause)] = 20,
			[typeof(ITF.EventSequenceControl)] = 44,
			[typeof(ITF.Actor)] = 776,
			[typeof(ITF.AnimLightComponent)] = 1312,
			[typeof(ITF.SubAnimSet)] = 608,
			[typeof(ITF.DialogActorComponent)] = 352,
			[typeof(ITF.COL_InteractComponent_Template)] = 68,
			[typeof(ITF.EventCameraShake)] = 24,
			[typeof(ITF.PlayLoop_evtTemplate)] = 68,
			[typeof(ITF.COL_FXListPlayerComponent_Template)] = 36,
			[typeof(ITF.COL_FXListPlayerComponent_Template.FXListEntry)] = 16,
			[typeof(ITF.AnimatedComponent)] = 1504,
			[typeof(ITF.CharacterDebuggerComponent)] = 288,
			[typeof(ITF.PhantomComponent)] = 352,
			[typeof(ITF.PlayerDetectorComponent)] = 1592,
			[typeof(ITF.COL_BattleTriggerComponent)] = 376,
			[typeof(ITF.COL_SpawnedNPCComponent)] = 20,
			[typeof(ITF.SoundComponent)] = 304,
			[typeof(ITF.COL_FeedbackControllerComponent)] = 360,
			[typeof(ITF.COL_BTAIComponent)] = 96,
			[typeof(ITF.COL_NPCAIData)] = 64,
			[typeof(ITF.COL_EventOffset)] = 20,
			[typeof(ITF.COL_CinematicDialogData.OverrideMood)] = 12,
			[typeof(ITF.BlendTreeNodeChooseBranch_Template<ITF.AnimTreeResult>)] = 128,
			[typeof(ITF.BlendTreeNodeChooseBranch_Template<ITF.AnimTreeResult>.BlendLeaf)] = 20,
			[typeof(ITF.CriteriaDesc)] = 24,
			[typeof(ITF.COL_LockCharacterEvent)] = 28,
			[typeof(ITF.COL_EventEnableWorldMap)] = 20,
			[typeof(ITF.COL_EventRichPresence)] = 20,
			[typeof(ITF.COL_CharacterInteractiveComponent_Template)] = 56,
			[typeof(ITF.Unknown_COL_20_sub_7CC7B0)] = 216,
			[typeof(ITF.EventSetText)] = 52,
			[typeof(ITF.SmartLocId)] = 32,
			[typeof(ITF.COL_EventMonitorComponent_Template)] = 16,
			[typeof(ITF.EventPadRumbleStop)] = 16,
			[typeof(ITF.EventSequenceActorActivate)] = 24,
			[typeof(ITF.EventReset)] = 16,
			[typeof(ITF.COL_TrapDelayComponent_Template)] = 16,
			[typeof(ITF.RelayEventInstanceComponent_Template)] = 16,
			[typeof(ITF.EventCheckpointReached)] = 16,
			[typeof(ITF.EventCheckpointTriggerSequence)] = 20,
			[typeof(ITF.COL_CharacterStatsDebugComponent_Template)] = 16,
			[typeof(ITF.AnimTreeNodeSequence_Template)] = 112,
			[typeof(ITF.BalloonComponent_Template)] = 36,
			[typeof(ITF.UITextBox_Template)] = 72,
			[typeof(ITF.RelayEventComponent_Template)] = 36,
			[typeof(ITF.RelayData)] = 36,
			[typeof(ITF.PloufComponent_Template)] = 24,
			[typeof(ITF.COL_EventHurt)] = 20,
			[typeof(ITF.COL_AnimatedWindComponent_Template)] = 36,
			[typeof(ITF.PhysForceModifierCircle_Template)] = 68,
			[typeof(ITF.PhysForceModifierBox_Template)] = 60,
			[typeof(ITF.PlayStory_evtTemplate)] = 180,
			[typeof(ITF.COL_EventDisableFlying)] = 16,
			[typeof(ITF.COL_EventEnableFlying)] = 16,
			[typeof(ITF.AlwaysActiveActorComponent_Template)] = 32,
			[typeof(ITF.COL_EventChangeAuroraVersion)] = 20,
			[typeof(ITF.COL_BattleCameraComponent_Template)] = 32,
			[typeof(ITF.COL_BattleCharacterSpawnSetupComponent_Template)] = 16,
			[typeof(ITF.COL_LightOrbSpawnerComponent_Template)] = 180,
			[typeof(ITF.COL_EventBattleIntroSequenceAnimStart)] = 16,
			[typeof(ITF.COL_EventBattleOutroSequenceAnimStart)] = 16,
			[typeof(ITF.COL_BattleFlowModifierComponent_Template)] = 16,
			[typeof(ITF.COL_BattleVisualManagerComponent_Template)] = 16,
			[typeof(ITF.ListenerComponent_Template)] = 24,
			[typeof(ITF.COL_CinematicDialogsUI_Template)] = 3440,
			[typeof(ITF.SaveNotificationComponent_Template)] = 28,
			[typeof(ITF.COL_BattleMenuActionBar_Template)] = 72,
			[typeof(ITF.COL_BattleActionBarComponent_Template)] = 80,
			[typeof(ITF.COL_CharacterInfoHUD_Template)] = 1796,
			[typeof(ITF.COL_UIProgressBar_Template)] = 52,
			[typeof(ITF.COL_FeedbackHUD_Template)] = 3284,
			[typeof(ITF.COL_TutorialHUD_Template)] = 72,
			[typeof(ITF.COL_Tutorial2DActorComponent_Template)] = 16,
			[typeof(ITF.FixedCameraComponent_Template)] = 32,
			[typeof(ITF.COL_PauseMenu_Template)] = 76,
			[typeof(ITF.UIItemBasic_Template)] = 176,
			[typeof(ITF.COL_UIPauseMenuButtonComponent_Template)] = 16,
			[typeof(ITF.COL_WorldMapMenu_Template)] = 72,
			[typeof(ITF.COL_WorldMapUIItem_Template)] = 184,
			[typeof(ITF.MultiTextureGraphicComponent_Template)] = 1828,
			[typeof(ITF.MultiTextureGraphicComponent_Template.MultiTextureEntry)] = 1736,
			[typeof(ITF.COL_BattleControllerComponent_Template)] = 16,
			[typeof(ITF.COL_BattleActionManagerComponent_Template)] = 16,
			[typeof(ITF.COL_BattleStatusComponent_Template)] = 16,
			[typeof(ITF.COL_BattleAIComponent_Template)] = 16,
			[typeof(ITF.COL_BattleAudioVisualComponent_Template)] = 24,
			[typeof(ITF.COL_CinematicDialogsUIComponent_Template)] = 36,
			[typeof(ITF.FontTemplate)] = 340,
			[typeof(ITF.Trail3DComponent_Template)] = 1836,
			[typeof(ITF.PhantomDetectorComponent_Template)] = 92,
			[typeof(ITF.COL_LightOrbComponent_Template)] = 160,
			[typeof(ITF.SpeedInputProviderComponent_Template)] = 48,
			[typeof(ITF.Trail_Template)] = 1724,
			[typeof(ITF.FontTemplate.Info)] = 96,
			[typeof(ITF.FontTemplate.Common)] = 40,
			[typeof(ITF.FontTemplate.Page)] = 104,
			[typeof(ITF.FontTemplate.Char)] = 40,
			[typeof(ITF.COL_ProjectileComponent_Template)] = 24,
			[typeof(ITF.StaticMeshVertexComponent_Template)] = 1804,


		};

		public static readonly Dictionary<Type, uint> RetailSizes = new Dictionary<Type, uint>() {
			// Main
			[typeof(StringID)] = 4,
			[typeof(Path)] = 144, // 140 + StringID
			[typeof(LocalizedPath)] = 148, // Path + LocId
			[typeof(LocalisationId)] = 4,
			[typeof(ColorInteger)] = 4,
			[typeof(string)] = 20,
			[typeof(Vec2d)] = 8,
			[typeof(Vec3d)] = 12,
			[typeof(Vec4d)] = 16,
			[typeof(Color)] = 16,
			[typeof(Angle)] = 4,
			[typeof(AngleAmount)] = 4,
			[typeof(ObjectId)] = 8,
			[typeof(ObjectRef)] = 4,
			[typeof(PathRef)] = 4,
			[typeof(Platform)] = 4,
			[typeof(SoundGUID)] = 4,
			[typeof(Volume)] = 4,

			// From IDA
		};

		public static readonly Dictionary<Type, uint> RetailAlign = new Dictionary<Type, uint>() {
			// ObjectFactory
			[typeof(ITF.Scene)] = 16,

			[typeof(ITF.COL_GameManager)] = 8,
			[typeof(ITF.COL_BaseInteractiveComponent)] = 8,
			[typeof(ITF.COL_BaseInteractiveComponentNew)] = 8,
			[typeof(ITF.COL_InteractiveObjectComponent)] = 8,
			[typeof(ITF.COL_TweenControllerComponent)] = 8,
			[typeof(ITF.COL_PlayerControllerComponent)] = 8,
			[typeof(ITF.COL_DarkCloudRepellerComponent)] = 16,
			[typeof(ITF.COL_DarkCloudSwarmComponent)] = 16,
			[typeof(ITF.COL_BattleTriggerComponent)] = 8,
			[typeof(ITF.COL_CinematicDialogsUI)] = 8,
			[typeof(ITF.COL_BattleAudioVisualComponent)] = 8,
			[typeof(ITF.COL_BattleXpGainedMenu)] = 8,
			[typeof(ITF.COL_BattleMenuActionSelection)] = 8,
			[typeof(ITF.COL_BattleMenuTargetSelection)] = 8,
			[typeof(ITF.COL_MainMenu)] = 8,
			[typeof(ITF.COL_LevelUpPopUp)] = 8,
			[typeof(ITF.COL_BattleScorePopUp)] = 8,
			[typeof(ITF.COL_InteractComponent)] = 8,
			[typeof(ITF.COL_MovableObjectInteractiveComponent)] = 8,
			[typeof(ITF.COL_PressurePlateComponent)] = 8,
			[typeof(ITF.COL_QuestGiverComponent)] = 8,
			[typeof(ITF.COL_QuestLocationComponent)] = 8,
			[typeof(ITF.COL_CreditsMenu)] = 8,
			[typeof(ITF.COL_CraftingMenu)] = 8,
			[typeof(ITF.COL_FeedbackControllerComponent)] = 8,
			[typeof(ITF.SwarmComponent)] = 16,
			[typeof(ITF.RenderBoxComponent)] = 16,
			[typeof(ITF.TweenComponent_Template)] = 8,
			[typeof(ITF.DetectorComponent)] = 8,
			[typeof(ITF.LogisticParams)] = 8,
			[typeof(ITF.Mesh3DComponent)] = 16,
			[typeof(ITF.ParticleGeneratorComponent)] = 16,
			[typeof(ITF.AtlasAnimationComponent)] = 16,
			[typeof(ITF.DataFluid)] = 8,
			[typeof(ITF.EdgeFluid)] = 8,
			[typeof(ITF.COL_LeverComponent)] = 8,
			[typeof(ITF.FXControllerComponent)] = 8,
			[typeof(ITF.AnimTreeNodePlayAnimProceduralSmooth_Template)] = 8,
			[typeof(ITF.AnimTreeNodePlayAnimInterpolateCursor_Template)] = 8,
			[typeof(ITF.AnimTreeNodePlayAnim_Template)] = 8,
			[typeof(ITF.TriggerComponent)] = 8,
			[typeof(ITF.PhantomTriggerComponent)] = 8,
			[typeof(ITF.AIComponent)] = 8,
			[typeof(ITF.DeathTriggerComponent)] = 8,
			[typeof(ITF.Animation3DTreeNodeSequence_Template)] = 8,
			[typeof(ITF.AnimTreeNodeSequence_Template)] = 8,
			[typeof(ITF.MusicTreeNodePlayMusic_Template)] = 8,
			[typeof(ITF.MusicTreeNodeRandom_Template)] = 8,
			[typeof(ITF.PlayTextBanner_evtTemplate)] = 8,
			[typeof(ITF.Animation3DTreeNodePlayAnim_Template)] = 8,
			[typeof(ITF.MusicTreeBlock_Template)] = 8,
			[typeof(ITF.MusicTreeBlockSequence_Template)] = 8,
			[typeof(ITF.MusicTreeBlockRandom_Template)] = 8,
			[typeof(ITF.CameraShakeCurveParams)] = 8,
			[typeof(ITF.COL_LightOrbComponent)] = 8,
			[typeof(ITF.DeformOnTrajectoryComponent)] = 8,
			[typeof(ITF.MusicTreeNode_Template)] = 8,
			[typeof(ITF.MusicTreeNodeComposite_Template)] = 8,
			[typeof(ITF.AnimTreeNodeRandomBranch_Template<AnimTreeResult>)] = 8,
			[typeof(ITF.AnimTreeNodeRandomBranch_Template<Animation3DTreeResult>)] = 8,
			[typeof(ITF.AnimTreeNodeBranchTransition_Template)] = 8,
			[typeof(ITF.Animation3DTreeNodePlaySynchAnim_Template)] = 8,
			[typeof(ITF.PlayerControllerComponent)] = 8,
			[typeof(ITF.AnimTreeNodeMarchBlend_Template)] = 8,
			[typeof(ITF.AnimTreeNodePlayOnOff_Template)] = 8,
			[typeof(ITF.BlendTreeNodeBranchTransition_Template<AnimTreeResult>)] = 8,
			[typeof(ITF.BlendTreeNodeBranchTransition_Template<Animation3DTreeResult>)] = 8,
			[typeof(ITF.BlendTreeNodeBranchTransition_Template<MusicTreeResult>)] = 8,
			[typeof(ITF.BlendTreeNodeBlendBranches_Template<AnimTreeResult>)] = 8,
			[typeof(ITF.BlendTreeNodeBlendBranches_Template<Animation3DTreeResult>)] = 8,
			[typeof(ITF.BlendTreeNodeBlendBranches_Template<MusicTreeResult>)] = 8,
			[typeof(ITF.BlendTreeNodeChooseBranch_Template<AnimTreeResult>)] = 8,
			[typeof(ITF.BlendTreeNodeChooseBranch_Template<Animation3DTreeResult>)] = 8,
			[typeof(ITF.BlendTreeNodeChooseBranch_Template<MusicTreeResult>)] = 8,
			[typeof(ITF.BlendTreeNodeAddBranch_Template<AnimTreeResult>)] = 8,
			[typeof(ITF.BlendTreeNodeAddBranch_Template<Animation3DTreeResult>)] = 8,
			[typeof(ITF.BlendTreeNodeAddBranch_Template<MusicTreeResult>)] = 8,
			[typeof(ITF.AdditionalBehaviorsComponent)] = 8,
			[typeof(ITF.BaseCurveParams)] = 8,
			[typeof(ITF.BankIdChange)] = 8,
			[typeof(ITF.SubAnimSet)] = 8,
			[typeof(ITF.CameraDetectorComponent)] = 8,
			[typeof(ITF.CameraModifierComponent)] = 8,
			[typeof(ITF.SubAnimSet_Template)] = 8,
			[typeof(ITF.COL_CharacterInteractiveComponent)] = 8,
			[typeof(ITF.AnimResourcePackage)] = 8,
			[typeof(ITF.AnimatedComponent_Template)] = 8,
			[typeof(ITF.AnimatedComponent)] = 8,
			[typeof(ITF.CameraShake)] = 8,
			[typeof(ITF.TimedSpawnerAIComponent)] = 8,
			[typeof(ITF.SequencePlayerComponent)] = 8,
			[typeof(ITF.AnimMeshVertexComponent_Template)] = 8,
			[typeof(ITF.COL_NavigationCameraComponent)] = 8,
			[typeof(ITF.InGameCameraComponent)] = 8,
			[typeof(ITF.AnimLightComponent_Template)] = 8,
			[typeof(ITF.AnimLightComponent)] = 8,
			[typeof(ITF.RopeComponent)] = 8,
			[typeof(ITF.BezierTreeRendererComponent)] = 8,
			[typeof(ITF.TrajectoryFollowerComponent)] = 8,
			[typeof(ITF.COL_LightOrbSpawnerComponent)] = 8,
			[typeof(ITF.LinkCurveComponent)] = 8,
			[typeof(ITF.COL_FeedbackTextBox)] = 8,
			[typeof(ITF.COL_SimplePatchComponent)] = 8,
			[typeof(ITF.HingePlatformComponent)] = 8,
			[typeof(ITF.SoftPlatformComponent)] = 8,
			[typeof(ITF.AxisPolylineComponent)] = 8,
			[typeof(ITF.RotatingPolylineComponent)] = 8,
			[typeof(ITF.SolidPolylineComponent)] = 8,
			[typeof(ITF.ProceduralSoftPlatformComponent)] = 8,
			[typeof(ITF.CharacterDebuggerComponent)] = 8,
			[typeof(ITF.MusicTreeNodeSequence_Template)] = 8,
			[typeof(ITF.TriggerOnButtonPressedComponent)] = 8,
			[typeof(ITF.BounceOnPolylinePhysComponent)] = 8,
			[typeof(ITF.GenericAIComponent)] = 8,
			[typeof(ITF.AnimMarkerTriggerComponent)] = 8,
			[typeof(ITF.ShapeDetectorComponent)] = 8,
			[typeof(ITF.PhantomDetectorComponent)] = 8,
			[typeof(ITF.EnemyDetectorComponent)] = 8,
			[typeof(ITF.DeathDetectorComponent)] = 8,
			[typeof(ITF.PlayerDetectorComponent)] = 8,
			[typeof(ITF.TouchDetectorComponent)] = 8,
			[typeof(ITF.FriezeContactDetectorComponent)] = 8,
			[typeof(ITF.PolylineComponent)] = 8,
			[typeof(ITF.PointsCollisionComponent)] = 8,
			[typeof(ITF.DetectorComponent)] = 8,

			// Not ObjectFactory
			[typeof(ITF.Trajectory)] = 16,
			[typeof(ITF.Message)] = 8,
			[typeof(ITF.UIScrollbar_Template.Style)] = 1,
			[typeof(ITF.Frise.MeshStaticData)] = 16,
			[typeof(ITF.Frise.MeshAnimData)] = 16,
			[typeof(ITF.Frise.MeshOverlayData)] = 16,
			[typeof(ITF.Frise.MeshFluidData)] = 8,
		};
		#endregion

		public const bool UseEditorSizes = true;

		public bool TryGetSize(Type type, out uint size) {
			uint? sizeOf = null;
			size = 0;
			if (Type.GetTypeCode(type) != TypeCode.Object) {
				sizeOf = 4;
				switch (Type.GetTypeCode(type)) {
					case TypeCode.Boolean: sizeOf = 4; break;
					case TypeCode.Byte: sizeOf = 1; break;
					case TypeCode.Char: sizeOf = 1; break;
					case TypeCode.String: sizeOf = 20; break; // sizeof(String8) // IN RL
					case TypeCode.Double: sizeOf = 8; break;
					case TypeCode.UInt16: sizeOf = 2; break;
					case TypeCode.UInt64: sizeOf = 8; break;
					case TypeCode.Int16: sizeOf = 2; break;
					case TypeCode.Int64: sizeOf = 8; break;
				}
			} else if (typeof(IObjectContainer).IsAssignableFrom(type)) {
				sizeOf = 4;
				if (type.IsGenericType) {
					var baseType = type.GetGenericTypeDefinition();
					// Could probably be written better
					if (baseType == typeof(CList<>) || baseType == typeof(CArray<>)
						|| baseType == typeof(CListO<>) || baseType == typeof(CListP<>) || baseType == typeof(CRefList<>)
						|| baseType == typeof(CArrayO<>) || baseType == typeof(CArrayP<>)) {
						sizeOf = 20;
					}
				}
			}
			
			if(!sizeOf.HasValue) {
				if (UseEditorSizes && EditorSizes.ContainsKey(type)) {
					sizeOf = EditorSizes[type];
				}
				if (!sizeOf.HasValue && RetailSizes.ContainsKey(type)) {
					sizeOf = RetailSizes[type];
				}
			}

			if (sizeOf.HasValue) {
				size = sizeOf.Value;
				return true;
			}
			return false;
		}


		public bool TryGetAlign(Type type, out uint align) {
			if (RetailAlign.ContainsKey(type)) {
				align = RetailAlign[type];
				return true;
			}
			align = 0;
			return false;
		}
	}
}