namespace UbiArt.ITF {
	public enum RLC_RewardType {
		[Serialize("RLC_RewardType_Unknown"              )] Unknown = 0,
		[Serialize("RLC_RewardType_Gems"                 )] Gems = 1,
		[Serialize("RLC_RewardType_Costume"              )] Costume = 2,
		[Serialize("RLC_RewardType_LuckyTicket"          )] LuckyTicket = 3,
		[Serialize("RLC_RewardType_GoldenTicket"         )] GoldenTicket = 4,
		[Serialize("RLC_RewardType_Region"               )] Region = 5,
		[Serialize("RLC_RewardType_CreatureFamily"       )] CreatureFamily = 6,
		[Serialize("RLC_RewardType_HunterLevel"          )] HunterLevel = 7,
		[Serialize("RLC_RewardType_Food"                 )] Food = 8,
		[Serialize("RLC_RewardType_Egg"                  )] Egg = 9,
		[Serialize("RLC_RewardType_Elixirs"              )] Elixirs = 10,
		[Serialize("RLC_RewardType_AllElixirPack"        )] AllElixirPack = 0xb,
		[Serialize("RLC_RewardType_TwoElixirs"           )] TwoElixirs = 0xc,
		[Serialize("RLC_RewardType_ThreeElixirs"         )] ThreeElixirs = 0xd,
		[Serialize("RLC_RewardType_BeatboxSaveSlots"     )] BeatboxSaveSlots = 0xe,
		[Serialize("RLC_RewardType_CreatureFamilyEvent"  )] CreatureFamilyEvent = 0xf,
		[Serialize("RLC_RewardType_SeasonalCurrency"     )] SeasonalCurrency = 0x10,
		[Serialize("RLC_RewardType_SeasonalTicket"       )] SeasonalTicket = 0x11,
		[Serialize("RLC_RewardType_SeasonalEgg"          )] SeasonalEgg = 0x12,
		[Serialize("RLC_RewardType_MagnifyingGlass"      )] MagnifyingGlass = 0x13,
		[Serialize("RLC_RewardType_DecoyEggBronze"       )] DecoyEggBronze = 0x14,
		[Serialize("RLC_RewardType_DecoyEggSilver"       )] DecoyEggSilver = 0x15,
		[Serialize("RLC_RewardType_DecoyEggGold"         )] DecoyEggGold = 0x16,
		[Serialize("RLC_RewardType_DecoyEggQueen"        )] DecoyEggQueen = 0x17,
		[Serialize("RLC_RewardType_ScoreRecapVideo"      )] ScoreRecapVideo = 0x18,
		[Serialize("RLC_RewardType_CreatureFamilyEndless")] CreatureFamilyEndless = 0x19,
		[Serialize("RLC_RewardType_ChallengeToken"       )] ChallengeToken = 0x1a,
		[Serialize("RLC_RewardType_ChallengeTicket"      )] ChallengeTicket = 0x1b,
		[Serialize("RLC_RewardType_ChallengeReward"      )] ChallengeReward = 0x1c,
		[Serialize("RLC_RewardType_SeasonalCurrency01"   )] SeasonalCurrency01 = 0x1d,
		[Serialize("RLC_RewardType_SeasonalCurrency02"   )] SeasonalCurrency02 = 0x1e,
		[Serialize("RLC_RewardType_SeasonalCurrency03"   )] SeasonalCurrency03 = 0x1f,
		[Serialize("RLC_RewardType_SeasonalCurrency04"   )] SeasonalCurrency04 = 0x20,
		[Serialize("RLC_RewardType_Count"                )] Count = 0x21,
	}
}

