namespace UbiArt.ITF {
	public enum RLC_GraphicalKit {
		[Serialize("RLC_GraphicalKit_Dojo")] RLC_GraphicalKit_Dojo = 1,
		[Serialize("RLC_GraphicalKit_SnowyMountain")] RLC_GraphicalKit_SnowyMountain = 2,
		[Serialize("RLC_GraphicalKit_BabelTower")] RLC_GraphicalKit_BabelTower = 3,
		[Serialize("RLC_GraphicalKit_LandOfTheDead")] RLC_GraphicalKit_LandOfTheDead = 4,
		[Serialize("RLC_GraphicalKit_CastleInterior")] RLC_GraphicalKit_CastleInterior = 5,
		[Serialize("RLC_GraphicalKit_CastleExterior")] RLC_GraphicalKit_CastleExterior = 6,
		[Serialize("RLC_GraphicalKit_Swamp")] RLC_GraphicalKit_Swamp = 7,
		[Serialize("RLC_GraphicalKit_EnchantedForest")] RLC_GraphicalKit_EnchantedForest = 8,
		[Serialize("RLC_GraphicalKit_BeanStalk")] RLC_GraphicalKit_BeanStalk = 9,
		[Serialize("RLC_GraphicalKit_Avatar")] RLC_GraphicalKit_Avatar = 10,
		[Serialize("RLC_GraphicalKit_OvergrownTemple")] RLC_GraphicalKit_OvergrownTemple = 11,
		[Serialize("RLC_GraphicalKit_MexicanParty")] RLC_GraphicalKit_MexicanParty = 12,
		[Serialize("RLC_GraphicalKit_CakeParty")] RLC_GraphicalKit_CakeParty = 13,
		[Serialize("RLC_GraphicalKit_Garbage")] RLC_GraphicalKit_Garbage = 14,
		[Serialize("RLC_GraphicalKit_Hangar")] RLC_GraphicalKit_Hangar = 15,
		[Serialize("RLC_GraphicalKit_Nemo")] RLC_GraphicalKit_Nemo = 16,
		[Serialize("RLC_GraphicalKit_Olympus")] RLC_GraphicalKit_Olympus = 17,
		[Serialize("RLC_GraphicalKit_Palace")] RLC_GraphicalKit_Palace = 18,
		[Serialize("RLC_GraphicalKit_Hades")] RLC_GraphicalKit_Hades = 19,
		[Serialize("RLC_GraphicalKit_Maze")] RLC_GraphicalKit_Maze = 20,
		[Serialize("RLC_GraphicalKit_Intro")] RLC_GraphicalKit_Intro = 21,
		[Serialize("RLC_GraphicalKit_HauntedCastle")] RLC_GraphicalKit_HauntedCastle = 22,
		[Serialize("RLC_GraphicalKit_DemoMix")] RLC_GraphicalKit_DemoMix = 23,
		[Serialize("RLC_GraphicalKit_Temple")] RLC_GraphicalKit_Temple = 24,
		[Serialize("RLC_GraphicalKit_OpenOcean")] RLC_GraphicalKit_OpenOcean = 25,
		[Serialize("RLC_GraphicalKit_AncientRuins")] RLC_GraphicalKit_AncientRuins = 26,
		[Serialize("RLC_GraphicalKit_Urban")] RLC_GraphicalKit_Urban = 27,
		[Serialize("RLC_GraphicalKit_Rural")] RLC_GraphicalKit_Rural = 28,
		[Serialize("RLC_GraphicalKit_Count")] RLC_GraphicalKit_Count = 29,
	}
}

