namespace UbiArt.ITF {
	public enum RLC_GraphicalKit {
		[Serialize("RLC_GraphicalKit_Dojo")] Dojo = 1,
		[Serialize("RLC_GraphicalKit_SnowyMountain")] SnowyMountain = 2,
		[Serialize("RLC_GraphicalKit_BabelTower")] BabelTower = 3,
		[Serialize("RLC_GraphicalKit_LandOfTheDead")] LandOfTheDead = 4,
		[Serialize("RLC_GraphicalKit_CastleInterior")] CastleInterior = 5,
		[Serialize("RLC_GraphicalKit_CastleExterior")] CastleExterior = 6,
		[Serialize("RLC_GraphicalKit_Swamp")] Swamp = 7,
		[Serialize("RLC_GraphicalKit_EnchantedForest")] EnchantedForest = 8,
		[Serialize("RLC_GraphicalKit_BeanStalk")] BeanStalk = 9,
		[Serialize("RLC_GraphicalKit_Avatar")] Avatar = 10,
		[Serialize("RLC_GraphicalKit_OvergrownTemple")] OvergrownTemple = 11,
		[Serialize("RLC_GraphicalKit_MexicanParty")] MexicanParty = 12,
		[Serialize("RLC_GraphicalKit_CakeParty")] CakeParty = 13,
		[Serialize("RLC_GraphicalKit_Garbage")] Garbage = 14,
		[Serialize("RLC_GraphicalKit_Hangar")] Hangar = 15,
		[Serialize("RLC_GraphicalKit_Nemo")] Nemo = 16,
		[Serialize("RLC_GraphicalKit_Olympus")] Olympus = 17,
		[Serialize("RLC_GraphicalKit_Palace")] Palace = 18,
		[Serialize("RLC_GraphicalKit_Hades")] Hades = 19,
		[Serialize("RLC_GraphicalKit_Maze")] Maze = 20,
		[Serialize("RLC_GraphicalKit_Intro")] Intro = 21,
		[Serialize("RLC_GraphicalKit_HauntedCastle")] HauntedCastle = 22,
		[Serialize("RLC_GraphicalKit_DemoMix")] DemoMix = 23,
		[Serialize("RLC_GraphicalKit_Temple")] Temple = 24,
		[Serialize("RLC_GraphicalKit_OpenOcean")] OpenOcean = 25,
		[Serialize("RLC_GraphicalKit_AncientRuins")] AncientRuins = 26,
		[Serialize("RLC_GraphicalKit_Urban")] Urban = 27,
		[Serialize("RLC_GraphicalKit_Rural")] Rural = 28,
		[Serialize("RLC_GraphicalKit_Count")] Count = 29,
	}
}

