namespace UbiArt.ITF {
	[Games(GameFlags.RO | GameFlags.LegendsAndUp)]
	public partial class GroundAIControllerComponent_Template : BaseAIControllerComponent_Template {
		public float walkForce = 500f;
		public float walkEfficiencyMaxSpeed = 5.43f;
		public Angle walkEfficiencyMinGroundAngle = 0.7853982f;
		public Angle walkEfficiencyMaxGroundAngle = 1.169371f;
		public float walkEfficiencyMinAngleMultiplier = 1f;
		public float walkEfficiencyMaxAngleMultiplier;
		public float walkMoveTargetMultiplierMin;
		public float walkMoveTargetMultiplierMax = 1f;
		public float walkMoveTargetBlendTime = 0.5f;
		public float airForce = 500f;
		public float airTopSpeed = 5f;
		public float airFriction = 2f;
		public float airSuspensionMinYSpeed = 4f;
		public float airSuspensionMaxYSpeed = 10f;
		public float airSuspensionMinMultiplier;
		public float airSuspensionMaxMultiplier = 0.92f;
		public float swimWaterResistMinSpeed = 4f;
		public float swimWaterResistMaxSpeed = 10f;
		public float swimWaterResistMaxMultiplier = 10f;
		public float swimJumpRange = 2f;
		public float swimInertiaSpeed = 8f;
		public float swimTopSpeed = 3f;
		public float swimTurnDistanceMultiplier = 50f;
		public float swimTurnSpeedMultiplier = 10f;
		public bool swimDisableRotation;
		public float flyInertiaSpeed;
		public float flyTopSpeed;
		public float jumpForce = 630f;
		public float jumpToActorYFuncPoint0Dist = 5f;
		public float jumpToActorYFuncPoint1Dist = 5f;
		public float jumpToActorXZFuncPoint0T = 0.3f;
		public float jumpToActorXZFuncPoint1T = 0.85f;
		public float jumpToActorSpeed = 20f;
		public float jumpToActorMinTime = 1f;
		public float avoidanceRadius = 0.8f;
		public float minVariation = 0.8f;
		public float maxVariation = 0.9f;
		public float sprintWalkForceMultiplier = 1f;
		public float sprintEfficiencyMaxSpeedMultiplier = 2f;
		public float sprintAccelerationDuration = 1.2f;
		public float dashSpeed = 100f;
		protected override void SerializeImpl(CSerializerObject s) {
			base.SerializeImpl(s);
			if (s.Settings.Game == Game.RO) {
				walkForce = s.Serialize<float>(walkForce, name: "walkForce");
				walkEfficiencyMaxSpeed = s.Serialize<float>(walkEfficiencyMaxSpeed, name: "walkEfficiencyMaxSpeed");
				walkEfficiencyMinGroundAngle = s.SerializeObject<Angle>(walkEfficiencyMinGroundAngle, name: "walkEfficiencyMinGroundAngle");
				walkEfficiencyMaxGroundAngle = s.SerializeObject<Angle>(walkEfficiencyMaxGroundAngle, name: "walkEfficiencyMaxGroundAngle");
				walkEfficiencyMinAngleMultiplier = s.Serialize<float>(walkEfficiencyMinAngleMultiplier, name: "walkEfficiencyMinAngleMultiplier");
				walkEfficiencyMaxAngleMultiplier = s.Serialize<float>(walkEfficiencyMaxAngleMultiplier, name: "walkEfficiencyMaxAngleMultiplier");
				walkMoveTargetMultiplierMin = s.Serialize<float>(walkMoveTargetMultiplierMin, name: "walkMoveTargetMultiplierMin");
				walkMoveTargetMultiplierMax = s.Serialize<float>(walkMoveTargetMultiplierMax, name: "walkMoveTargetMultiplierMax");
				walkMoveTargetBlendTime = s.Serialize<float>(walkMoveTargetBlendTime, name: "walkMoveTargetBlendTime");
				airForce = s.Serialize<float>(airForce, name: "airForce");
				airTopSpeed = s.Serialize<float>(airTopSpeed, name: "airTopSpeed");
				airFriction = s.Serialize<float>(airFriction, name: "airFriction");
				airSuspensionMinYSpeed = s.Serialize<float>(airSuspensionMinYSpeed, name: "airSuspensionMinYSpeed");
				airSuspensionMaxYSpeed = s.Serialize<float>(airSuspensionMaxYSpeed, name: "airSuspensionMaxYSpeed");
				airSuspensionMinMultiplier = s.Serialize<float>(airSuspensionMinMultiplier, name: "airSuspensionMinMultiplier");
				airSuspensionMaxMultiplier = s.Serialize<float>(airSuspensionMaxMultiplier, name: "airSuspensionMaxMultiplier");
				swimWaterResistMinSpeed = s.Serialize<float>(swimWaterResistMinSpeed, name: "swimWaterResistMinSpeed");
				swimWaterResistMaxSpeed = s.Serialize<float>(swimWaterResistMaxSpeed, name: "swimWaterResistMaxSpeed");
				swimWaterResistMaxMultiplier = s.Serialize<float>(swimWaterResistMaxMultiplier, name: "swimWaterResistMaxMultiplier");
				swimJumpRange = s.Serialize<float>(swimJumpRange, name: "swimJumpRange");
				swimInertiaSpeed = s.Serialize<float>(swimInertiaSpeed, name: "swimInertiaSpeed");
				swimTopSpeed = s.Serialize<float>(swimTopSpeed, name: "swimTopSpeed");
				swimTurnDistanceMultiplier = s.Serialize<float>(swimTurnDistanceMultiplier, name: "swimTurnDistanceMultiplier");
				swimTurnSpeedMultiplier = s.Serialize<float>(swimTurnSpeedMultiplier, name: "swimTurnSpeedMultiplier");
				jumpForce = s.Serialize<float>(jumpForce, name: "jumpForce");
				jumpToActorYFuncPoint0Dist = s.Serialize<float>(jumpToActorYFuncPoint0Dist, name: "jumpToActorYFuncPoint0Dist");
				jumpToActorYFuncPoint1Dist = s.Serialize<float>(jumpToActorYFuncPoint1Dist, name: "jumpToActorYFuncPoint1Dist");
				jumpToActorXZFuncPoint0T = s.Serialize<float>(jumpToActorXZFuncPoint0T, name: "jumpToActorXZFuncPoint0T");
				jumpToActorXZFuncPoint1T = s.Serialize<float>(jumpToActorXZFuncPoint1T, name: "jumpToActorXZFuncPoint1T");
				jumpToActorSpeed = s.Serialize<float>(jumpToActorSpeed, name: "jumpToActorSpeed");
				jumpToActorMinTime = s.Serialize<float>(jumpToActorMinTime, name: "jumpToActorMinTime");
				avoidanceRadius = s.Serialize<float>(avoidanceRadius, name: "avoidanceRadius");
				minVariation = s.Serialize<float>(minVariation, name: "minVariation");
				maxVariation = s.Serialize<float>(maxVariation, name: "maxVariation");
				sprintWalkForceMultiplier = s.Serialize<float>(sprintWalkForceMultiplier, name: "sprintWalkForceMultiplier");
				sprintEfficiencyMaxSpeedMultiplier = s.Serialize<float>(sprintEfficiencyMaxSpeedMultiplier, name: "sprintEfficiencyMaxSpeedMultiplier");
				sprintAccelerationDuration = s.Serialize<float>(sprintAccelerationDuration, name: "sprintAccelerationDuration");
			} else if (s.Settings.Game == Game.RL || s.Settings.Game == Game.COL || s.Settings.Game == Game.VH) {
				walkForce = s.Serialize<float>(walkForce, name: "walkForce");
				walkEfficiencyMaxSpeed = s.Serialize<float>(walkEfficiencyMaxSpeed, name: "walkEfficiencyMaxSpeed");
				walkEfficiencyMinGroundAngle = s.SerializeObject<Angle>(walkEfficiencyMinGroundAngle, name: "walkEfficiencyMinGroundAngle");
				walkEfficiencyMaxGroundAngle = s.SerializeObject<Angle>(walkEfficiencyMaxGroundAngle, name: "walkEfficiencyMaxGroundAngle");
				walkEfficiencyMinAngleMultiplier = s.Serialize<float>(walkEfficiencyMinAngleMultiplier, name: "walkEfficiencyMinAngleMultiplier");
				walkEfficiencyMaxAngleMultiplier = s.Serialize<float>(walkEfficiencyMaxAngleMultiplier, name: "walkEfficiencyMaxAngleMultiplier");
				walkMoveTargetMultiplierMin = s.Serialize<float>(walkMoveTargetMultiplierMin, name: "walkMoveTargetMultiplierMin");
				walkMoveTargetMultiplierMax = s.Serialize<float>(walkMoveTargetMultiplierMax, name: "walkMoveTargetMultiplierMax");
				walkMoveTargetBlendTime = s.Serialize<float>(walkMoveTargetBlendTime, name: "walkMoveTargetBlendTime");
				airForce = s.Serialize<float>(airForce, name: "airForce");
				airTopSpeed = s.Serialize<float>(airTopSpeed, name: "airTopSpeed");
				airFriction = s.Serialize<float>(airFriction, name: "airFriction");
				airSuspensionMinYSpeed = s.Serialize<float>(airSuspensionMinYSpeed, name: "airSuspensionMinYSpeed");
				airSuspensionMaxYSpeed = s.Serialize<float>(airSuspensionMaxYSpeed, name: "airSuspensionMaxYSpeed");
				airSuspensionMinMultiplier = s.Serialize<float>(airSuspensionMinMultiplier, name: "airSuspensionMinMultiplier");
				airSuspensionMaxMultiplier = s.Serialize<float>(airSuspensionMaxMultiplier, name: "airSuspensionMaxMultiplier");
				swimWaterResistMinSpeed = s.Serialize<float>(swimWaterResistMinSpeed, name: "swimWaterResistMinSpeed");
				swimWaterResistMaxSpeed = s.Serialize<float>(swimWaterResistMaxSpeed, name: "swimWaterResistMaxSpeed");
				swimWaterResistMaxMultiplier = s.Serialize<float>(swimWaterResistMaxMultiplier, name: "swimWaterResistMaxMultiplier");
				swimJumpRange = s.Serialize<float>(swimJumpRange, name: "swimJumpRange");
				swimInertiaSpeed = s.Serialize<float>(swimInertiaSpeed, name: "swimInertiaSpeed");
				swimTopSpeed = s.Serialize<float>(swimTopSpeed, name: "swimTopSpeed");
				swimTurnDistanceMultiplier = s.Serialize<float>(swimTurnDistanceMultiplier, name: "swimTurnDistanceMultiplier");
				swimTurnSpeedMultiplier = s.Serialize<float>(swimTurnSpeedMultiplier, name: "swimTurnSpeedMultiplier");
				swimDisableRotation = s.Serialize<bool>(swimDisableRotation, name: "swimDisableRotation");
				flyInertiaSpeed = s.Serialize<float>(flyInertiaSpeed, name: "flyInertiaSpeed");
				flyTopSpeed = s.Serialize<float>(flyTopSpeed, name: "flyTopSpeed");
				jumpForce = s.Serialize<float>(jumpForce, name: "jumpForce");
				jumpToActorYFuncPoint0Dist = s.Serialize<float>(jumpToActorYFuncPoint0Dist, name: "jumpToActorYFuncPoint0Dist");
				jumpToActorYFuncPoint1Dist = s.Serialize<float>(jumpToActorYFuncPoint1Dist, name: "jumpToActorYFuncPoint1Dist");
				jumpToActorXZFuncPoint0T = s.Serialize<float>(jumpToActorXZFuncPoint0T, name: "jumpToActorXZFuncPoint0T");
				jumpToActorXZFuncPoint1T = s.Serialize<float>(jumpToActorXZFuncPoint1T, name: "jumpToActorXZFuncPoint1T");
				jumpToActorSpeed = s.Serialize<float>(jumpToActorSpeed, name: "jumpToActorSpeed");
				jumpToActorMinTime = s.Serialize<float>(jumpToActorMinTime, name: "jumpToActorMinTime");
				avoidanceRadius = s.Serialize<float>(avoidanceRadius, name: "avoidanceRadius");
				minVariation = s.Serialize<float>(minVariation, name: "minVariation");
				maxVariation = s.Serialize<float>(maxVariation, name: "maxVariation");
				sprintWalkForceMultiplier = s.Serialize<float>(sprintWalkForceMultiplier, name: "sprintWalkForceMultiplier");
				sprintEfficiencyMaxSpeedMultiplier = s.Serialize<float>(sprintEfficiencyMaxSpeedMultiplier, name: "sprintEfficiencyMaxSpeedMultiplier");
				sprintAccelerationDuration = s.Serialize<float>(sprintAccelerationDuration, name: "sprintAccelerationDuration");
			} else {
				walkForce = s.Serialize<float>(walkForce, name: "walkForce");
				walkEfficiencyMaxSpeed = s.Serialize<float>(walkEfficiencyMaxSpeed, name: "walkEfficiencyMaxSpeed");
				walkEfficiencyMinGroundAngle = s.SerializeObject<Angle>(walkEfficiencyMinGroundAngle, name: "walkEfficiencyMinGroundAngle");
				walkEfficiencyMaxGroundAngle = s.SerializeObject<Angle>(walkEfficiencyMaxGroundAngle, name: "walkEfficiencyMaxGroundAngle");
				walkEfficiencyMinAngleMultiplier = s.Serialize<float>(walkEfficiencyMinAngleMultiplier, name: "walkEfficiencyMinAngleMultiplier");
				walkEfficiencyMaxAngleMultiplier = s.Serialize<float>(walkEfficiencyMaxAngleMultiplier, name: "walkEfficiencyMaxAngleMultiplier");
				walkMoveTargetMultiplierMin = s.Serialize<float>(walkMoveTargetMultiplierMin, name: "walkMoveTargetMultiplierMin");
				walkMoveTargetMultiplierMax = s.Serialize<float>(walkMoveTargetMultiplierMax, name: "walkMoveTargetMultiplierMax");
				walkMoveTargetBlendTime = s.Serialize<float>(walkMoveTargetBlendTime, name: "walkMoveTargetBlendTime");
				airForce = s.Serialize<float>(airForce, name: "airForce");
				airTopSpeed = s.Serialize<float>(airTopSpeed, name: "airTopSpeed");
				airFriction = s.Serialize<float>(airFriction, name: "airFriction");
				airSuspensionMinYSpeed = s.Serialize<float>(airSuspensionMinYSpeed, name: "airSuspensionMinYSpeed");
				airSuspensionMaxYSpeed = s.Serialize<float>(airSuspensionMaxYSpeed, name: "airSuspensionMaxYSpeed");
				airSuspensionMinMultiplier = s.Serialize<float>(airSuspensionMinMultiplier, name: "airSuspensionMinMultiplier");
				airSuspensionMaxMultiplier = s.Serialize<float>(airSuspensionMaxMultiplier, name: "airSuspensionMaxMultiplier");
				swimWaterResistMinSpeed = s.Serialize<float>(swimWaterResistMinSpeed, name: "swimWaterResistMinSpeed");
				swimWaterResistMaxSpeed = s.Serialize<float>(swimWaterResistMaxSpeed, name: "swimWaterResistMaxSpeed");
				swimWaterResistMaxMultiplier = s.Serialize<float>(swimWaterResistMaxMultiplier, name: "swimWaterResistMaxMultiplier");
				swimJumpRange = s.Serialize<float>(swimJumpRange, name: "swimJumpRange");
				swimInertiaSpeed = s.Serialize<float>(swimInertiaSpeed, name: "swimInertiaSpeed");
				swimTopSpeed = s.Serialize<float>(swimTopSpeed, name: "swimTopSpeed");
				swimTurnDistanceMultiplier = s.Serialize<float>(swimTurnDistanceMultiplier, name: "swimTurnDistanceMultiplier");
				swimTurnSpeedMultiplier = s.Serialize<float>(swimTurnSpeedMultiplier, name: "swimTurnSpeedMultiplier");
				swimDisableRotation = s.Serialize<bool>(swimDisableRotation, name: "swimDisableRotation");
				flyInertiaSpeed = s.Serialize<float>(flyInertiaSpeed, name: "flyInertiaSpeed");
				flyTopSpeed = s.Serialize<float>(flyTopSpeed, name: "flyTopSpeed");
				jumpForce = s.Serialize<float>(jumpForce, name: "jumpForce");
				jumpToActorYFuncPoint0Dist = s.Serialize<float>(jumpToActorYFuncPoint0Dist, name: "jumpToActorYFuncPoint0Dist");
				jumpToActorYFuncPoint1Dist = s.Serialize<float>(jumpToActorYFuncPoint1Dist, name: "jumpToActorYFuncPoint1Dist");
				jumpToActorXZFuncPoint0T = s.Serialize<float>(jumpToActorXZFuncPoint0T, name: "jumpToActorXZFuncPoint0T");
				jumpToActorXZFuncPoint1T = s.Serialize<float>(jumpToActorXZFuncPoint1T, name: "jumpToActorXZFuncPoint1T");
				jumpToActorSpeed = s.Serialize<float>(jumpToActorSpeed, name: "jumpToActorSpeed");
				jumpToActorMinTime = s.Serialize<float>(jumpToActorMinTime, name: "jumpToActorMinTime");
				avoidanceRadius = s.Serialize<float>(avoidanceRadius, name: "avoidanceRadius");
				minVariation = s.Serialize<float>(minVariation, name: "minVariation");
				maxVariation = s.Serialize<float>(maxVariation, name: "maxVariation");
				sprintWalkForceMultiplier = s.Serialize<float>(sprintWalkForceMultiplier, name: "sprintWalkForceMultiplier");
				sprintEfficiencyMaxSpeedMultiplier = s.Serialize<float>(sprintEfficiencyMaxSpeedMultiplier, name: "sprintEfficiencyMaxSpeedMultiplier");
				sprintAccelerationDuration = s.Serialize<float>(sprintAccelerationDuration, name: "sprintAccelerationDuration");
				dashSpeed = s.Serialize<float>(dashSpeed, name: "dashSpeed");
			}
		}
		public override uint? ClassCRC => 0x4530E988;
	}
}

