namespace UbiArt.ITF {
	[Games(GameFlags.VH)]
	public partial class W1W_Emile_Template : ActorComponent_Template {
		public WithAnimStateMachine_Template WithAnimStateMachine_Template__0;
		public float float__1;
		public float float__2;
		public float float__3;
		public float float__4;
		public float float__5;
		public float float__6;
		public float float__7;
		public float float__8;
		public float float__9;
		public float float__10;
		public float float__11;
		public float float__12;
		public float float__13;
		public float float__14;
		public float float__15;
		public float float__16;
		public float float__17;
		public float float__18;
		public float float__19;
		public float float__20;
		public float float__21;
		public float float__22;
		public float float__23;
		public float float__24;
		public float float__25;
		public float float__26;
		public float float__27;
		public Vec2d Vector2__28;
		public float float__29;
		public float float__30;
		public float float__31;
		public Curve2D Curve2D__32;
		public StringID StringID__33;
		public StringID StringID__34;
		public Path Path__35;
		public Path Path__36;
		public Path Path__37;
		public Path Path__38;
		public Path Path__39;
		public Path Path__40;
		public Path Path__41;
		public Vec2d Vector2__42;
		public Color Color__43;
		public Color Color__44;
		public float float__45;
		public float float__46;
		public float float__47;
		public float float__48;
		public float float__49;
		public Vec2d Vector2__50;
		public Vec2d Vector2__51;
		public float float__52;
		public Vec2d Vector2__53;
		public Path Path__54;
		protected override void SerializeImpl(CSerializerObject s) {
			base.SerializeImpl(s);
			WithAnimStateMachine_Template__0 = s.SerializeObject<WithAnimStateMachine_Template>(WithAnimStateMachine_Template__0, name: "WithAnimStateMachine_Template__0");
			float__1 = s.Serialize<float>(float__1, name: "float__1");
			float__2 = s.Serialize<float>(float__2, name: "float__2");
			float__3 = s.Serialize<float>(float__3, name: "float__3");
			float__4 = s.Serialize<float>(float__4, name: "float__4");
			float__5 = s.Serialize<float>(float__5, name: "float__5");
			float__6 = s.Serialize<float>(float__6, name: "float__6");
			float__7 = s.Serialize<float>(float__7, name: "float__7");
			float__8 = s.Serialize<float>(float__8, name: "float__8");
			float__9 = s.Serialize<float>(float__9, name: "float__9");
			float__10 = s.Serialize<float>(float__10, name: "float__10");
			float__11 = s.Serialize<float>(float__11, name: "float__11");
			float__12 = s.Serialize<float>(float__12, name: "float__12");
			float__13 = s.Serialize<float>(float__13, name: "float__13");
			float__14 = s.Serialize<float>(float__14, name: "float__14");
			float__15 = s.Serialize<float>(float__15, name: "float__15");
			float__16 = s.Serialize<float>(float__16, name: "float__16");
			float__17 = s.Serialize<float>(float__17, name: "float__17");
			float__18 = s.Serialize<float>(float__18, name: "float__18");
			float__19 = s.Serialize<float>(float__19, name: "float__19");
			float__20 = s.Serialize<float>(float__20, name: "float__20");
			float__21 = s.Serialize<float>(float__21, name: "float__21");
			float__22 = s.Serialize<float>(float__22, name: "float__22");
			float__23 = s.Serialize<float>(float__23, name: "float__23");
			float__24 = s.Serialize<float>(float__24, name: "float__24");
			float__25 = s.Serialize<float>(float__25, name: "float__25");
			float__26 = s.Serialize<float>(float__26, name: "float__26");
			float__27 = s.Serialize<float>(float__27, name: "float__27");
			Vector2__28 = s.SerializeObject<Vec2d>(Vector2__28, name: "Vector2__28");
			float__29 = s.Serialize<float>(float__29, name: "float__29");
			float__30 = s.Serialize<float>(float__30, name: "float__30");
			float__31 = s.Serialize<float>(float__31, name: "float__31");
			Curve2D__32 = s.SerializeObject<Curve2D>(Curve2D__32, name: "Curve2D__32");
			StringID__33 = s.SerializeObject<StringID>(StringID__33, name: "StringID__33");
			StringID__34 = s.SerializeObject<StringID>(StringID__34, name: "StringID__34");
			Path__35 = s.SerializeObject<Path>(Path__35, name: "Path__35");
			Path__36 = s.SerializeObject<Path>(Path__36, name: "Path__36");
			Path__37 = s.SerializeObject<Path>(Path__37, name: "Path__37");
			Path__38 = s.SerializeObject<Path>(Path__38, name: "Path__38");
			Path__39 = s.SerializeObject<Path>(Path__39, name: "Path__39");
			Path__40 = s.SerializeObject<Path>(Path__40, name: "Path__40");
			Path__41 = s.SerializeObject<Path>(Path__41, name: "Path__41");
			Vector2__42 = s.SerializeObject<Vec2d>(Vector2__42, name: "Vector2__42");
			Color__43 = s.SerializeObject<Color>(Color__43, name: "Color__43");
			Color__44 = s.SerializeObject<Color>(Color__44, name: "Color__44");
			float__45 = s.Serialize<float>(float__45, name: "float__45");
			float__46 = s.Serialize<float>(float__46, name: "float__46");
			float__47 = s.Serialize<float>(float__47, name: "float__47");
			float__48 = s.Serialize<float>(float__48, name: "float__48");
			float__49 = s.Serialize<float>(float__49, name: "float__49");
			Vector2__50 = s.SerializeObject<Vec2d>(Vector2__50, name: "Vector2__50");
			Vector2__51 = s.SerializeObject<Vec2d>(Vector2__51, name: "Vector2__51");
			float__52 = s.Serialize<float>(float__52, name: "float__52");
			Vector2__53 = s.SerializeObject<Vec2d>(Vector2__53, name: "Vector2__53");
			Path__54 = s.SerializeObject<Path>(Path__54, name: "Path__54");
		}
		public override uint? ClassCRC => 0x734C6562;
	}
}

